import "./css/style.css";

import { Inter } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
			>
				<div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
					{children}
				</div>
				<script
					defer
					src="https://cloud.umami.is/script.js"
					data-website-id="29fe9d00-ff33-47fa-acc7-e6ea7ebcf526"
				/>
			</body>
		</html>
	);
}
